---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@641e8b22034b8eb49e2bbc11ef103d1324eb93e2 # main
    name: Module Validation
    with:
      working-directory: .

  python-format:
    name: Python Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python format
        run: |
          make format-python
      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Code is not formatted. Please run 'make python-format' and commit the changes."
            exit 1
          fi

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python lint
        run: |
          make python-lint
